class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.6.92.tar.gz"
  sha256 "260b9e62053a2382694ac4149252267723a713d7ec9b5356fbb3f0330cd76ae0"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "4c64685bb5fd5fbe4c3a3cb7995eb474de868b35a6a39e32c817ba655333ab86"
    sha256 cellar: :any_skip_relocation, arm64_tahoe:       "4c64685bb5fd5fbe4c3a3cb7995eb474de868b35a6a39e32c817ba655333ab86"
    sha256 cellar: :any_skip_relocation, arm64_sequoia:     "4c64685bb5fd5fbe4c3a3cb7995eb474de868b35a6a39e32c817ba655333ab86"
    sha256 cellar: :any_skip_relocation, arm64_linux:       "816d97a74a3bf03916028a493430a55afdd7b3b4e360440bf4c48ee410ba4ef2"
    sha256 cellar: :any,                 x86_64_linux:      "7efcf134f89054708c48a6feb15e331b09c18e8f6e9a8df4e5cdcf34b2b38d05"
  end

  depends_on "go" => :build

  deny_network_access!

  def fetch
    system "go", "mod", "download"
  end

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
